USE [master]
GO

/****** Object:  Database [Smart Painting]    Script Date: 14/05/2018 17:45:49 ******/
CREATE DATABASE [Smart Painting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Smart Painting', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Smart Painting.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Smart Painting_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Smart Painting_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Smart Painting] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Smart Painting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Smart Painting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Smart Painting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Smart Painting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Smart Painting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Smart Painting] SET ARITHABORT OFF 
GO

ALTER DATABASE [Smart Painting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Smart Painting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Smart Painting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Smart Painting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Smart Painting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Smart Painting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Smart Painting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Smart Painting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Smart Painting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Smart Painting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Smart Painting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Smart Painting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Smart Painting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Smart Painting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Smart Painting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Smart Painting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Smart Painting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Smart Painting] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Smart Painting] SET  MULTI_USER 
GO

ALTER DATABASE [Smart Painting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Smart Painting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Smart Painting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Smart Painting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Smart Painting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Smart Painting] SET QUERY_STORE = OFF
GO

USE [Smart Painting]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Smart Painting] SET  READ_WRITE 
GO

